import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/provider/toastProvider";
import NextAuthSessionProvider from "@/provider/nextAuthSessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#0B101B] font-Inter">
      <ToastProvider/>
      <NextAuthSessionProvider>
        {children}
        </NextAuthSessionProvider>
        
        </body>
    </html>
  );
}
